spring:
  application:
    name: dan-gfm-service
  kafka:
    consumer:
      group-id: ${spring.application.name}
      properties:
        spring.json.trusted.packages: com.danservice.*
      # auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      retries: 3
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

dan:
  topic:
    street-order: dan-street-orders
    client-order: dan-client-orders